import json

from utils.engine import get_overall_score

data = {
    "suppliers": [
    {
        "Supplier Name": "TCS elastic_franklin",
        "Country": "Algeria",
        "Service": "Applications Development",
        "Avg. Cost($)": 143601,
        "Rating": 80,
        "Average Delivery Time": 151,
        "Number of Escalations": 308,
        "Year": 2021,
        "Resources": 6064,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS vigorous_bhabha",
        "Country": "Algeria",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 256872,
        "Rating": 92,
        "Average Delivery Time": 231,
        "Number of Escalations": 129,
        "Year": 2020,
        "Resources": 6361,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS zen_lalande",
        "Country": "Algeria",
        "Service": "Mainframe services",
        "Avg. Cost($)": 280612,
        "Rating": 95,
        "Average Delivery Time": 292,
        "Number of Escalations": 411,
        "Year": 2016,
        "Resources": 789,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS tender_hawking",
        "Country": "Algeria",
        "Service": "Service Desk",
        "Avg. Cost($)": 351708,
        "Rating": 79,
        "Average Delivery Time": 318,
        "Number of Escalations": 246,
        "Year": 2006,
        "Resources": 7626,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS condescending_goldstine",
        "Country": "Algeria",
        "Service": "Managed Services",
        "Avg. Cost($)": 157687,
        "Rating": 90,
        "Average Delivery Time": 137,
        "Number of Escalations": 319,
        "Year": 2021,
        "Resources": 2895,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS frosty_leakey",
        "Country": "Algeria",
        "Service": "Support",
        "Avg. Cost($)": 335415,
        "Rating": 79,
        "Average Delivery Time": 295,
        "Number of Escalations": 426,
        "Year": 2013,
        "Resources": 1292,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS brave_murdock",
        "Country": "Angola",
        "Service": "Applications Development",
        "Avg. Cost($)": 484120,
        "Rating": 78,
        "Average Delivery Time": 392,
        "Number of Escalations": 208,
        "Year": 2014,
        "Resources": 1409,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS sharp_mclaren",
        "Country": "Angola",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 206043,
        "Rating": 75,
        "Average Delivery Time": 173,
        "Number of Escalations": 84,
        "Year": 2013,
        "Resources": 7280,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS focused_mcclintock",
        "Country": "Angola",
        "Service": "Mainframe services",
        "Avg. Cost($)": 83187,
        "Rating": 98,
        "Average Delivery Time": 81,
        "Number of Escalations": 297,
        "Year": 2021,
        "Resources": 3725,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS upbeat_noyce",
        "Country": "Angola",
        "Service": "Service Desk",
        "Avg. Cost($)": 31779,
        "Rating": 92,
        "Average Delivery Time": 33,
        "Number of Escalations": 390,
        "Year": 2016,
        "Resources": 7095,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS vibrant_driscoll",
        "Country": "Angola",
        "Service": "Managed Services",
        "Avg. Cost($)": 354522,
        "Rating": 80,
        "Average Delivery Time": 322,
        "Number of Escalations": 104,
        "Year": 2011,
        "Resources": 892,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS silly_faraday",
        "Country": "Angola",
        "Service": "Support",
        "Avg. Cost($)": 48392,
        "Rating": 86,
        "Average Delivery Time": 46,
        "Number of Escalations": 416,
        "Year": 2017,
        "Resources": 2400,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS friendly_ishizaka",
        "Country": "Benin",
        "Service": "Applications Development",
        "Avg. Cost($)": 461320,
        "Rating": 71,
        "Average Delivery Time": 380,
        "Number of Escalations": 149,
        "Year": 2013,
        "Resources": 2279,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS condescending_aryabhata",
        "Country": "Benin",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 306079,
        "Rating": 75,
        "Average Delivery Time": 307,
        "Number of Escalations": 191,
        "Year": 2020,
        "Resources": 3278,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS wizardly_wescoff",
        "Country": "Benin",
        "Service": "Mainframe services",
        "Avg. Cost($)": 125145,
        "Rating": 99,
        "Average Delivery Time": 103,
        "Number of Escalations": 384,
        "Year": 2008,
        "Resources": 6726,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS dazzling_agnesi",
        "Country": "Benin",
        "Service": "Service Desk",
        "Avg. Cost($)": 87952,
        "Rating": 91,
        "Average Delivery Time": 92,
        "Number of Escalations": 276,
        "Year": 2019,
        "Resources": 1306,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS festive_zhukovsky",
        "Country": "Benin",
        "Service": "Managed Services",
        "Avg. Cost($)": 195264,
        "Rating": 83,
        "Average Delivery Time": 216,
        "Number of Escalations": 82,
        "Year": 2019,
        "Resources": 688,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS peaceful_cannon",
        "Country": "Benin",
        "Service": "Support",
        "Avg. Cost($)": 123371,
        "Rating": 74,
        "Average Delivery Time": 107,
        "Number of Escalations": 366,
        "Year": 2002,
        "Resources": 5869,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS friendly_black",
        "Country": "Botswana",
        "Service": "Applications Development",
        "Avg. Cost($)": 182427,
        "Rating": 96,
        "Average Delivery Time": 147,
        "Number of Escalations": 370,
        "Year": 2010,
        "Resources": 1060,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS dazzling_almeida",
        "Country": "Botswana",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 417652,
        "Rating": 84,
        "Average Delivery Time": 386,
        "Number of Escalations": 90,
        "Year": 2011,
        "Resources": 2580,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS adoring_kapitsa",
        "Country": "Botswana",
        "Service": "Mainframe services",
        "Avg. Cost($)": 121002,
        "Rating": 99,
        "Average Delivery Time": 129,
        "Number of Escalations": 170,
        "Year": 2021,
        "Resources": 763,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS vigorous_turing",
        "Country": "Botswana",
        "Service": "Service Desk",
        "Avg. Cost($)": 238650,
        "Rating": 85,
        "Average Delivery Time": 215,
        "Number of Escalations": 272,
        "Year": 2004,
        "Resources": 4300,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS affectionate_austin",
        "Country": "Botswana",
        "Service": "Managed Services",
        "Avg. Cost($)": 337554,
        "Rating": 81,
        "Average Delivery Time": 342,
        "Number of Escalations": 176,
        "Year": 2010,
        "Resources": 3663,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS kind_lovelace",
        "Country": "Botswana",
        "Service": "Support",
        "Avg. Cost($)": 471240,
        "Rating": 97,
        "Average Delivery Time": 396,
        "Number of Escalations": 28,
        "Year": 2009,
        "Resources": 7833,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS intelligent_joliot",
        "Country": "Burkina Faso",
        "Service": "Applications Development",
        "Avg. Cost($)": 307026,
        "Rating": 93,
        "Average Delivery Time": 333,
        "Number of Escalations": 252,
        "Year": 2004,
        "Resources": 2383,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS quizzical_mirzakhani",
        "Country": "Burkina Faso",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 155052,
        "Rating": 80,
        "Average Delivery Time": 146,
        "Number of Escalations": 499,
        "Year": 2008,
        "Resources": 8248,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS clever_tharp",
        "Country": "Burkina Faso",
        "Service": "Mainframe services",
        "Avg. Cost($)": 291165,
        "Rating": 81,
        "Average Delivery Time": 295,
        "Number of Escalations": 499,
        "Year": 2008,
        "Resources": 6857,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS adoring_keller",
        "Country": "Burkina Faso",
        "Service": "Service Desk",
        "Avg. Cost($)": 257414,
        "Rating": 94,
        "Average Delivery Time": 226,
        "Number of Escalations": 414,
        "Year": 2019,
        "Resources": 1222,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS boring_greider",
        "Country": "Burkina Faso",
        "Service": "Managed Services",
        "Avg. Cost($)": 25110,
        "Rating": 71,
        "Average Delivery Time": 27,
        "Number of Escalations": 232,
        "Year": 2019,
        "Resources": 4687,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS sweet_robinson",
        "Country": "Burkina Faso",
        "Service": "Support",
        "Avg. Cost($)": 50149,
        "Rating": 77,
        "Average Delivery Time": 47,
        "Number of Escalations": 192,
        "Year": 2011,
        "Resources": 8874,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS keen_hofstadter",
        "Country": "Burundi",
        "Service": "Applications Development",
        "Avg. Cost($)": 358380,
        "Rating": 94,
        "Average Delivery Time": 330,
        "Number of Escalations": 257,
        "Year": 2006,
        "Resources": 2282,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS amazing_keller",
        "Country": "Burundi",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 258060,
        "Rating": 71,
        "Average Delivery Time": 220,
        "Number of Escalations": 457,
        "Year": 2009,
        "Resources": 8204,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS upbeat_mayer",
        "Country": "Burundi",
        "Service": "Mainframe services",
        "Avg. Cost($)": 277574,
        "Rating": 82,
        "Average Delivery Time": 242,
        "Number of Escalations": 361,
        "Year": 2021,
        "Resources": 8675,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS fervent_driscoll",
        "Country": "Burundi",
        "Service": "Service Desk",
        "Avg. Cost($)": 213305,
        "Rating": 93,
        "Average Delivery Time": 185,
        "Number of Escalations": 162,
        "Year": 2006,
        "Resources": 1053,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS cranky_goldwasser",
        "Country": "Burundi",
        "Service": "Managed Services",
        "Avg. Cost($)": 61557,
        "Rating": 85,
        "Average Delivery Time": 51,
        "Number of Escalations": 278,
        "Year": 2007,
        "Resources": 7018,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS recursing_elion",
        "Country": "Burundi",
        "Service": "Support",
        "Avg. Cost($)": 371472,
        "Rating": 83,
        "Average Delivery Time": 327,
        "Number of Escalations": 285,
        "Year": 2004,
        "Resources": 4191,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS keen_wu",
        "Country": "Cameroon",
        "Service": "Applications Development",
        "Avg. Cost($)": 240108,
        "Rating": 76,
        "Average Delivery Time": 204,
        "Number of Escalations": 324,
        "Year": 2016,
        "Resources": 2069,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS exciting_hoover",
        "Country": "Cameroon",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 197788,
        "Rating": 81,
        "Average Delivery Time": 197,
        "Number of Escalations": 333,
        "Year": 2004,
        "Resources": 1973,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS musing_lamport",
        "Country": "Cameroon",
        "Service": "Mainframe services",
        "Avg. Cost($)": 163485,
        "Rating": 83,
        "Average Delivery Time": 135,
        "Number of Escalations": 152,
        "Year": 2021,
        "Resources": 1391,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS youthful_ardinghelli",
        "Country": "Cameroon",
        "Service": "Service Desk",
        "Avg. Cost($)": 197181,
        "Rating": 81,
        "Average Delivery Time": 201,
        "Number of Escalations": 481,
        "Year": 2010,
        "Resources": 5582,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS blissful_bohr",
        "Country": "Cameroon",
        "Service": "Managed Services",
        "Avg. Cost($)": 47806,
        "Rating": 73,
        "Average Delivery Time": 41,
        "Number of Escalations": 288,
        "Year": 2021,
        "Resources": 3447,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS modest_antonelli",
        "Country": "Cameroon",
        "Service": "Support",
        "Avg. Cost($)": 240084,
        "Rating": 95,
        "Average Delivery Time": 247,
        "Number of Escalations": 447,
        "Year": 2016,
        "Resources": 1871,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS youthful_gagarin",
        "Country": "Cape Verde",
        "Service": "Applications Development",
        "Avg. Cost($)": 84084,
        "Rating": 91,
        "Average Delivery Time": 84,
        "Number of Escalations": 111,
        "Year": 2008,
        "Resources": 1545,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS competent_clarke",
        "Country": "Cape Verde",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 43738,
        "Rating": 87,
        "Average Delivery Time": 38,
        "Number of Escalations": 338,
        "Year": 2019,
        "Resources": 5767,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS dazzling_blackwell",
        "Country": "Cape Verde",
        "Service": "Mainframe services",
        "Avg. Cost($)": 479199,
        "Rating": 99,
        "Average Delivery Time": 399,
        "Number of Escalations": 421,
        "Year": 2021,
        "Resources": 6634,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS romantic_franklin",
        "Country": "Cape Verde",
        "Service": "Service Desk",
        "Avg. Cost($)": 456547,
        "Rating": 84,
        "Average Delivery Time": 377,
        "Number of Escalations": 351,
        "Year": 2012,
        "Resources": 2702,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS suspicious_chaum",
        "Country": "Cape Verde",
        "Service": "Managed Services",
        "Avg. Cost($)": 217364,
        "Rating": 74,
        "Average Delivery Time": 196,
        "Number of Escalations": 238,
        "Year": 2021,
        "Resources": 5353,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS angry_mestorf",
        "Country": "Cape Verde",
        "Service": "Support",
        "Avg. Cost($)": 169214,
        "Rating": 98,
        "Average Delivery Time": 146,
        "Number of Escalations": 500,
        "Year": 2012,
        "Resources": 5972,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS kind_newton",
        "Country": "Central African Republic",
        "Service": "Applications Development",
        "Avg. Cost($)": 246375,
        "Rating": 87,
        "Average Delivery Time": 219,
        "Number of Escalations": 217,
        "Year": 2019,
        "Resources": 3910,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS festive_swartz",
        "Country": "Central African Republic",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 178038,
        "Rating": 76,
        "Average Delivery Time": 162,
        "Number of Escalations": 51,
        "Year": 2002,
        "Resources": 747,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS gracious_hoover",
        "Country": "Central African Republic",
        "Service": "Mainframe services",
        "Avg. Cost($)": 276148,
        "Rating": 76,
        "Average Delivery Time": 262,
        "Number of Escalations": 383,
        "Year": 2015,
        "Resources": 4579,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS boring_hoover",
        "Country": "Central African Republic",
        "Service": "Service Desk",
        "Avg. Cost($)": 162778,
        "Rating": 71,
        "Average Delivery Time": 154,
        "Number of Escalations": 349,
        "Year": 2019,
        "Resources": 3835,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS xenodochial_chatelet",
        "Country": "Central African Republic",
        "Service": "Managed Services",
        "Avg. Cost($)": 83922,
        "Rating": 89,
        "Average Delivery Time": 71,
        "Number of Escalations": 480,
        "Year": 2007,
        "Resources": 2634,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS funny_borg",
        "Country": "Central African Republic",
        "Service": "Support",
        "Avg. Cost($)": 163582,
        "Rating": 71,
        "Average Delivery Time": 178,
        "Number of Escalations": 479,
        "Year": 2014,
        "Resources": 7767,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS vibrant_driscoll",
        "Country": "Chad",
        "Service": "Applications Development",
        "Avg. Cost($)": 359676,
        "Rating": 74,
        "Average Delivery Time": 291,
        "Number of Escalations": 444,
        "Year": 2014,
        "Resources": 8950,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS busy_bartik",
        "Country": "Chad",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 141432,
        "Rating": 71,
        "Average Delivery Time": 142,
        "Number of Escalations": 398,
        "Year": 2003,
        "Resources": 6420,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS musing_cerf",
        "Country": "Chad",
        "Service": "Mainframe services",
        "Avg. Cost($)": 259154,
        "Rating": 78,
        "Average Delivery Time": 214,
        "Number of Escalations": 329,
        "Year": 2020,
        "Resources": 7784,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS gifted_galois",
        "Country": "Chad",
        "Service": "Service Desk",
        "Avg. Cost($)": 418041,
        "Rating": 98,
        "Average Delivery Time": 351,
        "Number of Escalations": 120,
        "Year": 2021,
        "Resources": 2838,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS nervous_vaughan",
        "Country": "Chad",
        "Service": "Managed Services",
        "Avg. Cost($)": 252442,
        "Rating": 91,
        "Average Delivery Time": 226,
        "Number of Escalations": 176,
        "Year": 2009,
        "Resources": 6800,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS confident_williams",
        "Country": "Chad",
        "Service": "Support",
        "Avg. Cost($)": 249660,
        "Rating": 72,
        "Average Delivery Time": 228,
        "Number of Escalations": 223,
        "Year": 2017,
        "Resources": 3630,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS distracted_rhodes",
        "Country": "Comoros",
        "Service": "Applications Development",
        "Avg. Cost($)": 462553,
        "Rating": 75,
        "Average Delivery Time": 391,
        "Number of Escalations": 46,
        "Year": 2002,
        "Resources": 8641,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS practical_jang",
        "Country": "Comoros",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 265574,
        "Rating": 91,
        "Average Delivery Time": 214,
        "Number of Escalations": 97,
        "Year": 2017,
        "Resources": 2717,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS great_goodall",
        "Country": "Comoros",
        "Service": "Mainframe services",
        "Avg. Cost($)": 382776,
        "Rating": 77,
        "Average Delivery Time": 389,
        "Number of Escalations": 250,
        "Year": 2015,
        "Resources": 2082,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS intelligent_hertz",
        "Country": "Comoros",
        "Service": "Service Desk",
        "Avg. Cost($)": 299970,
        "Rating": 90,
        "Average Delivery Time": 297,
        "Number of Escalations": 127,
        "Year": 2018,
        "Resources": 6002,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS peaceful_pike",
        "Country": "Comoros",
        "Service": "Managed Services",
        "Avg. Cost($)": 173888,
        "Rating": 89,
        "Average Delivery Time": 143,
        "Number of Escalations": 334,
        "Year": 2017,
        "Resources": 1965,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS awesome_curie",
        "Country": "Comoros",
        "Service": "Support",
        "Avg. Cost($)": 42152,
        "Rating": 70,
        "Average Delivery Time": 44,
        "Number of Escalations": 317,
        "Year": 2019,
        "Resources": 3464,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS upbeat_poitras",
        "Country": "Cote d'Ivoire",
        "Service": "Applications Development",
        "Avg. Cost($)": 253105,
        "Rating": 97,
        "Average Delivery Time": 227,
        "Number of Escalations": 188,
        "Year": 2016,
        "Resources": 5511,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS confident_burnell",
        "Country": "Cote d'Ivoire",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 187052,
        "Rating": 71,
        "Average Delivery Time": 202,
        "Number of Escalations": 211,
        "Year": 2012,
        "Resources": 6514,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS interesting_leakey",
        "Country": "Cote d'Ivoire",
        "Service": "Mainframe services",
        "Avg. Cost($)": 242060,
        "Rating": 70,
        "Average Delivery Time": 245,
        "Number of Escalations": 419,
        "Year": 2018,
        "Resources": 801,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS busy_joliot",
        "Country": "Cote d'Ivoire",
        "Service": "Service Desk",
        "Avg. Cost($)": 100254,
        "Rating": 90,
        "Average Delivery Time": 98,
        "Number of Escalations": 202,
        "Year": 2010,
        "Resources": 1195,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS thirsty_torvalds",
        "Country": "Cote d'Ivoire",
        "Service": "Managed Services",
        "Avg. Cost($)": 165410,
        "Rating": 89,
        "Average Delivery Time": 139,
        "Number of Escalations": 97,
        "Year": 2003,
        "Resources": 6656,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS jovial_knuth",
        "Country": "Cote d'Ivoire",
        "Service": "Support",
        "Avg. Cost($)": 364428,
        "Rating": 88,
        "Average Delivery Time": 318,
        "Number of Escalations": 380,
        "Year": 2009,
        "Resources": 6945,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS eager_volhard",
        "Country": "Democratic Republic of the Congo",
        "Service": "Applications Development",
        "Avg. Cost($)": 230140,
        "Rating": 79,
        "Average Delivery Time": 185,
        "Number of Escalations": 287,
        "Year": 2019,
        "Resources": 5728,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS tender_swanson",
        "Country": "Democratic Republic of the Congo",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 67480,
        "Rating": 95,
        "Average Delivery Time": 56,
        "Number of Escalations": 180,
        "Year": 2011,
        "Resources": 510,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS adoring_diffie",
        "Country": "Democratic Republic of the Congo",
        "Service": "Mainframe services",
        "Avg. Cost($)": 270684,
        "Rating": 95,
        "Average Delivery Time": 219,
        "Number of Escalations": 105,
        "Year": 2010,
        "Resources": 5127,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS epic_hodgkin",
        "Country": "Democratic Republic of the Congo",
        "Service": "Service Desk",
        "Avg. Cost($)": 62075,
        "Rating": 75,
        "Average Delivery Time": 65,
        "Number of Escalations": 241,
        "Year": 2003,
        "Resources": 4693,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS competent_galileo",
        "Country": "Democratic Republic of the Congo",
        "Service": "Managed Services",
        "Avg. Cost($)": 398008,
        "Rating": 87,
        "Average Delivery Time": 344,
        "Number of Escalations": 206,
        "Year": 2016,
        "Resources": 7301,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS optimistic_rosalind",
        "Country": "Democratic Republic of the Congo",
        "Service": "Support",
        "Avg. Cost($)": 227368,
        "Rating": 71,
        "Average Delivery Time": 194,
        "Number of Escalations": 349,
        "Year": 2005,
        "Resources": 1888,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS affectionate_dijkstra",
        "Country": "Djibouti",
        "Service": "Applications Development",
        "Avg. Cost($)": 87542,
        "Rating": 71,
        "Average Delivery Time": 74,
        "Number of Escalations": 100,
        "Year": 2018,
        "Resources": 3410,
        "Rank": "1"
    },
    {
        "Supplier Name": "TCS dazzling_heyrovsky",
        "Country": "Djibouti",
        "Service": "Applications Maintenance",
        "Avg. Cost($)": 314160,
        "Rating": 81,
        "Average Delivery Time": 308,
        "Number of Escalations": 450,
        "Year": 2017,
        "Resources": 2561,
        "Rank": "1"
    }],
    "filters": {
        "Service": "Applications Development",
    },
    "attributes": {
        "Rating": {
            "Objective": "Maximize",
            "Weightage": 30,
            "tends_to_value": 100,
        },
        "Resources": {
            "Objective": "Minimize",
            "Weightage": 10,
            "tends_to_value": 1,
        },
        "Avg. Cost($)": {
            "Objective": "Minimize",
            "Weightage": 25,
            "tends_to_value": 1,
        },
        "Average Delivery Time": {
            "Objective": "Minimize",
            "Weightage": 20,
            "tends_to_value": 1,
        },
        "Number of Escalations": {
            "Objective": "Minimize",
            "Weightage": 15,
            "tends_to_value": 1,
        }
    }
}

filters = {
      "Service": {
          "criteria": "==",
          "value": "Applications Development"
      },
      "Average Delivery Time": {
          "criteria": "<=",
          "value": 30
      }
   }

attributes = {
    "Rating": {
        "Objective": "Maximize",
        "Weightage": 30,
        "tends_to_value": 100,
    },
    "Resources": {
        "Objective": "Minimize",
        "Weightage": 10,
        "tends_to_value": 1,
    },
    "Avg. Cost($)": {
        "Objective": "Minimize",
        "Weightage": 25,
        "tends_to_value": 1,
    },
    "Average Delivery Time": {
        "Objective": "Minimize",
        "Weightage": 20,
        "tends_to_value": 1,
    },
    "Number of Escalations": {
        "Objective": "Minimize",
        "Weightage": 15,
        "tends_to_value": 1,
    }
}
json_data_path = f'/Users/vigneswaran/Projects/sirion/SupplierPerformance/sample_data/all_suppliers.json'
with open(json_data_path, 'r') as f:
    supplier_data = json.load(f)
print(get_overall_score(supplier_data, filters, attributes))


# pareToTest1759

# mongoimport --host ac-czsi2w9-shard-00-02.lkpj03b.mongodb.net:27017 --db supliers --type json --file "/Users/vigneswaran/Projects/sirion/SupplierPerformance/sample_data/all_suppliers.json" --jsonArray --authenticationDatabase admin --ssl --username VigneswaranB97 --password pareToTest1759